- name: default
  type: sqlite
  database: dataset.db
  entities:
    - "src/entities/*.ts"
    - "src/entities/*.js"
  migrations:
    - "migrations/*.ts"
    - "migrations/*.js"
  cli:
    migrationsDir: migrations